### ISSUE TITLE
Out of date /renamed content

### ISSUE THREAD

**Issue by Mark-v-S** [JaKooLit/NixOS-Hyprland#15]
at least at auto-instal on NixOS 1 package and 1 font got renamed so 
qt5ct needs to be renamed to libsForQt5.qt5ct,
and noto-fonts-cjk is now called noto-fonts-cjk-sans

>  its nothing big but aint too easy to fix while downloding looking at you need to time when to edit and cant do it prior I would make a Pull request but I am new to nix and need to lern it first I am studing with c# thats all new

![image](https://github.com/user-attachments/assets/1b7cd615-0fec-4096-810f-c14605a8de46)
![image](https://github.com/user-attachments/assets/bdb10bd4-a090-42dd-a19a-a6b90b16eefc)

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/NixOS-Hyprland/commit/a4c659854492366800d946d0d4400096056a34d6

thanks bro. Much appreciated
