### ISSUE TITLE
[Bug]: qt5ct package renamed  errors on builds   error: 'qt5ct' has been renamed to/replaced by 'libsForQt5.qt5ct'

### ISSUE THREAD

**Issue by dwilliam62** [JaKooLit/NixOS-Hyprland#16]
## Bug Report
 
![image](https://github.com/user-attachments/assets/1b38f4da-7160-4662-9411-59808a9b94f4)

### Description

 Upstream change (again)   

 I moved my system packages to a system.packages.nix file.   I removed them from the host configs to make it easier to add / remove packages.  Like in this case I only need edit one file. 

### Steps to Reproduce

 1.)  Make mistake of choosing NIX.  HAHA 
 2.)  2nd mistake did follow item 1 ;) 
 3.)   update the flake

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/NixOS-Hyprland/commit/a4c659854492366800d946d0d4400096056a34d6

**Comment by JaKooLit** [comment]
dup

https://github.com/JaKooLit/NixOS-Hyprland/issues/15
