### ISSUE TITLE
[Bug]: Font noto-sans renamed   error: 'noto-fonts-cjk' has been renamed to/replaced by 'noto-fonts-cjk-sans'

### ISSUE THREAD

**Issue by dwilliam62** [JaKooLit/NixOS-Hyprland#17]
## Bug Report
 
 Another package renamed 

 error: 'noto-fonts-cjk' has been renamed to/replaced by 'noto-fonts-cjk-sans'

![image](https://github.com/user-attachments/assets/ecab0549-f08b-4c6f-9ff9-c7683b5b7992)

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/NixOS-Hyprland/commit/a4c659854492366800d946d0d4400096056a34d6

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/NixOS-Hyprland/issues/15
