### ISSUE TITLE
Tool missing 

### ISSUE THREAD

**Issue by daedaevibin** [JaKooLit/NixOS-Hyprland#7]
/etc/profiles/per-user/(user) does not exist and never has.

/etc/profiles/per-user/root   did but when logged in as a user that's not root it doesn't exist

**Comment by JaKooLit** [comment]
?

On readme, there never was mentioned about /etc


https://youtu.be/nJLnRgnLPWI

**Comment by daedaevibin** [comment]
> ?
> 
> On readme, there never was mentioned about /etc
> 
> 
> https://youtu.be/nJLnRgnLPWI

It showed up when running the script. Something to do with starship that doesn't exist

**Comment by JaKooLit** [comment]
suggest you auto install first and then remove / add package later once up and running

I dont use starship nor set up as such so I wouldnt know

**Comment by daedaevibin** [comment]
> suggest you auto install first and then remove / add package later once up and running
> 
> I dont use starship nor set up as such so I wouldnt know

I was just entirely confused as to what was happening.

NixOS was causing too many issues back to back let alone it took me 5+ hours to get it working to begin with. I'm never touching it again.
