### ISSUE TITLE
Graphical Glitches

### ISSUE THREAD

**Issue by 0x733** [JaKooLit/NixOS-Hyprland#8]
I didn't experience such an issue with Hyprland when I was using my Arch Linux configuration before. Since switching to NixOS, I've been encountering graphical glitches in applications like Brave Browser, Ferdium, and Ungoogled Chromium. I've checked the GPU drivers and the Hyprland configuration, but I couldn't find any issues. Could you help me out?

![image](https://github.com/user-attachments/assets/48e0fb96-3086-4717-b6dc-c6b2477b9e9f)

**Comment by JaKooLit** [comment]
Pls note that this NixOS-Hyprland is pulling the mainstream version or -git version of hyprland and aquamarine.

You can try to update your Arch to -git versions of hyprland and aquamarine. If you experience same, then it could be a bug either on hyprland / aquamarine or its a just because of Electron version

All of the apps you mentioned are ELECTRON Based so this suspect me that its electron issue

**Comment by 0x733** [comment]
I used your configuration on both Arch Linux and NixOS. Just for testing, I used the ZaneyOS configuration that you referenced in your NixOS setup, and I didn’t encounter this issue there. I couldn’t find any settings related to visuals in the ZaneyOS configuration that are missing here either.

**Comment by JaKooLit** [comment]
> I used your configuration on both Arch Linux and NixOS. Just for testing, I used the ZaneyOS configuration that you referenced in your NixOS setup, and I didn’t encounter this issue there. I couldn’t find any settings related to visuals in the ZaneyOS configuration that are missing here either.

its not about the configuration but its about the hyprland package..

Glad you mentioned about ZaneyOS cause if I remember it correctly, he didnt configure with hyprland-git version


Thats why I ask you to install the hyprland-git and aquamarine-git version on Arch to test if its because of the hyprland-git only and not with non-git hyprland

**Comment by 0x733** [comment]
> not



Unfortunately, I can't test it on Arch Linux, as I have NixOS installed on my system and don't have sufficient hardware to run a virtual machine. However, I resolved the issue using the command 'chromium --use-gl=egl --enable-features=UseOzonePlatform --ozone-platform=wayland'. I used the same command for Ferdium and Brave, and the issue didn't reoccur on those either. How can I make it permanent?

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/NixOS-Hyprland/blob/main/hosts%2Fdefault%2Fconfig.nix#L486

the last part should be already enabled by default.

for adding a flag to chromium. I will wait for others to mentioned as I have no clue how to

**Comment by 0x733** [comment]
> https://github.com/JaKooLit/NixOS-Hyprland/blob/main/hosts%2Fdefault%2Fconfig.nix#L486
> 
> 
> 
> the last part should be already enabled by default.
> 
> 
> 
> for adding a flag to chromium. I will wait for others to mentioned as I have no clue how to

I think this issue is related to OpenGL because when I use the following commands:

- `chromium --enable-features=UseOzonePlatform --ozone-platform=x11` 
- or `chromium --enable-features=UseOzonePlatform --ozone-platform=wayland` 

the problem persists. However, when I add the `--use-gl=egl` parameter to these commands, the issue is resolved.

**Comment by JaKooLit** [comment]
you can try to use "software" only

https://github.com/JaKooLit/Hyprland-Dots/blob/main/config%2Fhypr%2FUserConfigs%2FENVariables.conf

obviously, apply that to your ~/.config

**Comment by 0x733** [comment]
> you can try to use "software" only
> 
> https://github.com/JaKooLit/Hyprland-Dots/blob/main/config%2Fhypr%2FUserConfigs%2FENVariables.conf
> 
> obviously, apply that to your ~/.config
> 
> 
> but beware, its gonna be "global"

I'm writing it as `env = ELECTRON_DEFAULT_GL,egl`, but the issue persists. Am I making a mistake somewhere?

**Comment by 0x733** [comment]
When I enabled this setting (https://github.com/JaKooLit/Hyprland-Dots/blob/c612535e921d5b38c84b043250d1dc830a4dacb1/config/hypr/UserConfigs/ENVariables.conf#L47), the issue was resolved.  
Thank you very much for everything.  
The issue can be closed.
