### ISSUE TITLE
[Feature Request]: Use nixos.png for the logo when staring a shell 

### ISSUE THREAD

**Issue by dwilliam62** [JaKooLit/NixOS-Hyprland#9]
### Description

Currently you use the ascii logo for nixos when starting a kitty.  

 with the 'type: small" flag the ascii art is very aliased 

IMO this looks much better 

![image](https://github.com/user-attachments/assets/291b065c-2851-43bc-896b-2d6f10db8af7)

### Use Case

More aesthetically pleasing.  And the image is already there in the fastfetch folder. 

### Proposed Solution

``` "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
    "logo": {
      "source": "~/.config/fastfetch/nixos.png",
    	"type": "kitty-direct",
      "height": 10,
      "width": 18,
        "padding": {
            "top": 2
        },
       //  "type": "small"
    },```

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/NixOS-Hyprland/commit/ff84d0218b1352c14e17e366c0ee99f08c013221

forgot to close this
